name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project Package.swift -scheme NetHub -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=15.5' build test
